### ISSUE TITLE
Request to use HydroTouch Terminology

### ISSUE THREAD

**Issue by yuuiko** [dnnsmnstrr/dotfiles#3]
Hi, Dennis!

I've just joined GitHub and as you have seen, I have started to make a repository for AquaTouch. I saw your HydroTouch repo here, and I quite like how you set out your wiki. Do you mind if I borrow a few things from your HydroTouch wiki to put into my new repo? 
I'm not so great at phrasing things, and I'm quite fond of the way you explained some of AQT's features over there.

**Comment by dnnsmnstrr** [comment]
Go ahead, use whatever you like!
I'm working on a release for this project as well, just changed it to be more of an extension to your work. Maybe we can collaborate some more, I'll happily look over your explanations if you'd like. 😄
